version: "3.9"
services:
  app:
    build:
      context: .
    container_name: foxypoor_app
    restart: unless-stopped
    environment:
      - APP_ENV=prod
      - TELEGRAM_TOKEN
      - TELEGRAM_USER_ID
      - DATABASE_URL
      - APP_SECRET
      - EXPENSE_TIMEZONE
    logging: &default_logging
      driver: json-file
      options:
        max-size: "1m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    volumes:
      - db-data:/app/var/

volumes:
  db-data:
    driver: local



